/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { submissionItemsControllerFindAll } from '../fn/submissionitems-controller/submission-items-controller-find-all';
import { SubmissionItemsControllerFindAll$Params } from '../fn/submissionitems-controller/submission-items-controller-find-all';
import { submissionItemsControllerFindOne } from '../fn/submissionitems-controller/submission-items-controller-find-one';
import { SubmissionItemsControllerFindOne$Params } from '../fn/submissionitems-controller/submission-items-controller-find-one';

@Injectable({ providedIn: 'root' })
export class SubmissionitemsControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `submissionItemsControllerFindAll()` */
  static readonly SubmissionItemsControllerFindAllPath = '/submissionitems';

  /**
   * Get all submissionitems.
   *
   * Returns all the submissionitems available in the database
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `submissionItemsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  submissionItemsControllerFindAll$Response(params?: SubmissionItemsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return submissionItemsControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all submissionitems.
   *
   * Returns all the submissionitems available in the database
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `submissionItemsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  submissionItemsControllerFindAll(params?: SubmissionItemsControllerFindAll$Params, context?: HttpContext): Observable<void> {
    return this.submissionItemsControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `submissionItemsControllerFindOne()` */
  static readonly SubmissionItemsControllerFindOnePath = '/submissionitems/{id}';

  /**
   * Get one submissionitem.
   *
   * Returns the submissionitem with the specific ID in the database
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `submissionItemsControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  submissionItemsControllerFindOne$Response(params: SubmissionItemsControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return submissionItemsControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * Get one submissionitem.
   *
   * Returns the submissionitem with the specific ID in the database
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `submissionItemsControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  submissionItemsControllerFindOne(params: SubmissionItemsControllerFindOne$Params, context?: HttpContext): Observable<void> {
    return this.submissionItemsControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
