/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { workspacesControllerFindAll } from '../fn/workspaces-controller/workspaces-controller-find-all';
import { WorkspacesControllerFindAll$Params } from '../fn/workspaces-controller/workspaces-controller-find-all';
import { workspacesControllerFindOne } from '../fn/workspaces-controller/workspaces-controller-find-one';
import { WorkspacesControllerFindOne$Params } from '../fn/workspaces-controller/workspaces-controller-find-one';

@Injectable({ providedIn: 'root' })
export class WorkspacesControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `workspacesControllerFindAll()` */
  static readonly WorkspacesControllerFindAllPath = '/workspaces';

  /**
   * Get all workspaces.
   *
   * Returns all the workspaces available in the database
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workspacesControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  workspacesControllerFindAll$Response(params?: WorkspacesControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return workspacesControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all workspaces.
   *
   * Returns all the workspaces available in the database
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workspacesControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  workspacesControllerFindAll(params?: WorkspacesControllerFindAll$Params, context?: HttpContext): Observable<void> {
    return this.workspacesControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `workspacesControllerFindOne()` */
  static readonly WorkspacesControllerFindOnePath = '/workspaces/{id}';

  /**
   * Get one workspace.
   *
   * Returns the workspace with the specific ID in the database
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workspacesControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  workspacesControllerFindOne$Response(params: WorkspacesControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return workspacesControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * Get one workspace.
   *
   * Returns the workspace with the specific ID in the database
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workspacesControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  workspacesControllerFindOne(params: WorkspacesControllerFindOne$Params, context?: HttpContext): Observable<void> {
    return this.workspacesControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
